Big June 2021 PR
duckietown/challenge-aido_LF-template-ros pull request #11
Opened 2021-06-27 14:46 UTC by AndreaCensi

Mother issue: https://ethidsc.atlassian.net/browse/DTSW-990

2021-09-07 16:11 UTC, afdaniele requested changes

2021-09-07 16:11 UTC, afdaniele commented on Dockerfile
> +          libgif-dev\
@AndreaCensi format line

2021-09-07 16:11 UTC, afdaniele commented on Dockerfile
> +RUN echo we have PIP_INDEX_URL=${PIP_INDEX_URL} $PIP_INDEX_URL $DOCKER_REGISTRY
@AndreaCensi  do we need this?

2021-09-07 16:11 UTC, afdaniele commented on Dockerfile
> +RUN env
@AndreaCensi  do we need these?

2021-09-07 16:11 UTC, afdaniele commented on Dockerfile
> +#RUN python3 -m pip check # XXX: fails
remove

2021-09-07 16:11 UTC, afdaniele commented on Dockerfile
> +RUN python3 -m pip list
@AndreaCensi merge into a single `RUN` statement, reduces the number of layers

2021-09-07 16:11 UTC, afdaniele commented on Dockerfile
> +#RUN python3 -m pip install pillow --user --upgrade
remove

2021-09-07 16:11 UTC, afdaniele commented on submission_ws/src/agent/include/rosagent/rosagent.py
> +        # add the handlers to the logger
@AndreaCensi remove?

2021-09-07 16:11 UTC, afdaniele commented on submission_ws/src/agent/include/rosagent/rosagent.py
> +        # rospy.logerr('Errors still show up')
remove

2021-09-07 16:11 UTC, afdaniele commented on submission_ws/src/agent/src/solution.py
> +        # context.info(f'received obs camera {camera.timestamp} odometry {odometry.timestamp}')
remove

2021-09-07 16:11 UTC, afdaniele commented on submission_ws/src/agent/src/solution.py
> +        # context.info(f'on_received_get_commands')
remove

2021-09-16 16:37 UTC, AndreaCensi commented on Dockerfile
> +RUN echo we have PIP_INDEX_URL=${PIP_INDEX_URL} $PIP_INDEX_URL $DOCKER_REGISTRY
debugging

2021-09-16 16:37 UTC, AndreaCensi commented on Dockerfile
> +RUN env
debugging

2021-10-16 18:52 UTC, merged